apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: frontend-podkill
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: frontend
  duration: "30s"