apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-failure
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: redis-cart
  duration: "30s"